## Base URL for the site
baseURL = 'https://gerardo-alcazar.github.io/blog/'
## Site title
title = 'El Blog de Gerardo'
## Use hugo-brewm theme
theme = 'hugo-brewm'
## Enable Git information for pages
enableGitInfo = true
## Convert all URLs to absolute URLs
canonifyURLs = true
## Default language for content
defaultContentLanguage = 'en'
## Put default language in subdirectory
defaultContentLanguageInSubdir = false
## Use sections for main menu
sectionPagesMenu = 'main'

[params]
    ## Site title
    title = "El Blog de Gerardo"
    ## Site description
    description = "Mi rincón en internet sobre tecnología y más."
    ## Copyright notice
    copyright = "© 2026 Gerardo Alcazar"
    unifiedFooter = true

    ## Author information
    [params.author]
        ## site author's name
        name = 'Gerardo Alcazar'
        ## Author's email
        email = 'gerardoalcazar.contacto@gmail.com'


    ## Comments configuration
    [params.comments]
        ## Disable comments (disable fediverse comments)
        disabled = false
        ## Comment platform selection, currently only 'fediverse' is supported, further options to be determined
        # platform = 'fediverse'

    ## Fediverse integration settings
    [params.fediverse]
        ## Fediverse instance URL
        # instance = 'example.com'
        ## Fediverse username
        # username = 'username'

    ## Giscus integration settings
    # [params.giscus]
    #     repo = "foxihd/hugo-brewm"
    #     repoID = "R_kgDONwvqMA"
    #     category = "Articles"
    #     categoryID = "DIC_kwDONwvqMM4CnXDQ"

    ## Logo configuration
    [params.logo]
        ## Light mode logo mark
        # logoMark = 'https://example.com/logoMark.svg'
        ## Dark mode logo mark
        # logoMarkDark = 'https://example.com/logoMarkDark.svg'
        ## Enable logo type
        logoType = true

    ## Feed display settings
    [params.feed]
        ## Enable flowlines
        flowlines = true
        ## Limit number of flowlines
        flowlinesLimit = 21

    ## Home page display settings
    [params.home]
        ## Enable slide has-crsl
        disableSlide = false
        ## Enable taxonomy listing has-crsl
        disableListing = false
        ## Select taxonomy listing to be featured
        featuredListing = ['categories', 'series']

    ## Post display settings
    [params.posts]
        ## Enable text justification
        justifying = false
        ## Disable paragraph indentation
        noIndent = false
        ## Use sans-serif fonts as default
        sfdefault = false
        ## Show colophon section (including QR code)
        colophon = false
        ## disable redaction history
        disableHistory = true
        ## Show related content
        related = false
        ## override maximum series/related post count
        # RelatedLimit = 5
        ## Show share buttons
        share = false

[[menu.footer]]
    name = "Instagram"
    url = "https://www.instagram.com/_gerardo_alcazar_"
    weight = 1

    ## Search configuration
    [params.search]
        ## Enable search functionality, please index your site first
        enable = true
        ## Use pagefind search when javascript enabled, currently only 'pagefind' is supported, further options to be determined
        pagefind = true
        ## fallback searchbox when javascript disabled, currently the options limited to 'mojeek', otherwise duckduckgo will be used
        # fallback = 'mojeek'

    ## Typography settings
    [params.typeface]
        ## Use web safe fonts (will overide font selection below)
        webSafe = false
        ## Serif font selection
        roman = 'crimson'
        ## Sans-serif font selection
        sans = 'inter'
        ## use typeface stored in local server (pleaase download font's uri first)
        localHost = false

    ## Extended Metadata and  Social card configuration
    [params.socialCard]
        ## Enable twitter and opengraph social cards (same .params.extMeta setting)
        enable = true
        ## Default social card image
        images = "https://repository-images.githubusercontent.com/923527728/46a32a19-69ac-45b3-91a4-c4d299fb234b" ## recommended resolution: 1200 x 630px

        ## Enable Twitter cards
        # twitter = true
        ## Twitter creator handle
        # twitterCreator = "@username"
        ## Twitter site handle
        # twitterSite = "@username"

        ## Enable OpenGraph
        # opengraph = true
        ## Facebook App ID
        # facebookAppID = "123456789"
        ## Facebook Admin ID
        # facebookAdmin = "USER_ID"

        ## Schema.org (only meta, not fully supported)
        # schema = true
        ## JsonLD (cannot validate permalink)
        # jsonLD = true